# Generated by Django 3.2.9 on 2024-05-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='accounted_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flower',
            name='actual_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
