# Generated by Django 3.2.9 on 2024-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240517_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
    ]
