# Generated by Django 3.2.9 on 2024-05-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240518_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дом'),
        ),
    ]
